CLASS /ccbji/cx_fsv_stlmnt DEFINITION
  PUBLIC
  INHERITING FROM cx_rap_query_provider
  CREATE PUBLIC.

  PUBLIC SECTION.
  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.


CLASS /ccbji/cx_fsv_stlmnt IMPLEMENTATION.
ENDCLASS.
